services:
  feed_service:
    build:
      dockerfile: feed_service/Dockerfile
    container_name: feed_service
    ports:
      - "5001:5001"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://softarch:123456@postgres_db:5432/twitter2
    networks:
      - mynetwork

  message_service:
    build:
     dockerfile: message_service/Dockerfile

    container_name: message_service
    ports:
      - "5002:5002"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://softarch:123456@postgres_db:5432/twitter2  
    networks:
      - mynetwork

  user_service:
    build:
      dockerfile: user_service/Dockerfile

    container_name: user_service
    ports:
      - "5003:5003"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://softarch:123456@postgres_db:5432/twitter2
    networks:
      - mynetwork
 

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: softarch
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: twitter2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork


volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
